name: Deploy to VPS

# Pipeline aktif setiap kali ada push ke branch 'main'
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Executing Remote SSH Commands
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          # Masuk ke folder proyek di VPS
          cd /var/www/web/sajakcodingan-docker/backend-mystock
          
          # Ambil update kode terbaru dari GitHub
          git pull origin main
          
          # Rebuild image Docker dan jalankan ulang container di background
          docker compose up -d --build
          
          # Bersihkan image/cache Docker lama agar RAM 2GB tetap aman
          docker image prune -af