name: Deploy to VPS

# Pipeline aktif setiap kali ada push ke branch 'main'
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Executing Remote SSH Commands
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          # 1. Masuk ke folder UTAMA proyek (tempat file docker-compose.yml berada)
          cd /var/www/web/sajakcodingan-docker/backend-mystock
          
          # 2. Ambil update kode terbaru dari GitHubok
          git pull origin main
          
          # 3. Jalankan ulang container Flask agar Gunicorn memuat kode baru
          docker restart mystock-backend
          
          # 4. Bersihkan image/cache Docker lama agar RAM 2GB tetap aman
          docker image prune -f
